### ISSUE TITLE
Compilation fails on Linux with GCC

### ISSUE THREAD

**Issue by doronAtuar** [ConorStokes/LZSSE#10]
It seems like
`#include <string.h>`
Is missing in main.cpp and lzsse*.cpp

**Comment by ConorStokes** [comment]
What version of gcc/distro? It's building for me on gcc (7 and 8) on ubuntu. I can add the include, but it should be redundant with memory.h included.

**Comment by ConorStokes** [comment]
Also, are you using the gmake premake target? Or something else?

**Comment by ConorStokes** [comment]
I've changed the memory.h includes to string.h, which hasn't impacted any of my build tests - so I've pushed the change. Let me know if it fixes your issue (but also, still let me know gcc version etc for future reference).

**Comment by doronAtuar** [comment]
I'm using GCC 5.4.0
Ubuntu 16
And yes, I compiled using the generated gmake produced by premake

**Comment by ConorStokes** [comment]
If you wanted to do that, I'd be happy to take the patch.

> 
> 
> FWIW, I'd be willing to add support for Travis CI (to test various versions of GCC and clang, and maybe PGI) to this repo, but it hardly seems worth it considering the amount of activity this repo sees…

**Comment by ConorStokes** [comment]
I used gcc 5 (albeit on Ubuntu 18) and couldn't reproduce. Does the latest commit fix the issue?

> 
> I'm using GCC 5.4.0 Ubuntu 16 And yes, I compiled using the generated gmake produced by premake

**Comment by doronAtuar** [comment]
Yes, it did!
Thank you
